version: '3.8'

volumes:
  mongo:
services:
  nginx:
    image: nginx:mainline-alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "8000:80"
    depends_on:
    - api
    - frontend
  frontend:
    build:
      context: frontend
  api:
    build:
      context: api
    environment:
      MONGO_URL: mongodb://mongo:27017
    depends_on:
    - mongo
  mongo:
    image: mongo:4.4.4
    command: mongod --bind_ip_all --port 27017 --replSet rs0 --dbpath /data/db
    hostname: mongo
    ports:
    - "27017:27017"
    volumes:
    - mongo:/data/db
